import json
import re
from pathlib import Path

import yaml

from ..config import load_config

KEY_METRICS = ["mpjpe", "pa_mpjpe", "mpjre", "lowerpe", "handpe", "pred_jitter", "local_mpjpe_cm"]
IGNORE = {"data.processed", "data.calib", "data.smpl", "data.num_workers", "threads", "device", "train.log_every", "train_image.log_every", "model.image_features", "model.init_from", "model.image.init_from"}


def _flatten(d, prefix=""):
    out = {}
    for k, v in d.items():
        key = f"{prefix}{k}"
        if isinstance(v, dict):
            out.update(_flatten(v, key + "."))
        else:
            out[key] = v
    return out


def config_diff(run_cfg, base_cfg):
    a, b = _flatten(run_cfg), _flatten(base_cfg)
    diff = {k: v for k, v in a.items() if k not in IGNORE and b.get(k, "<absent>") != v}
    return diff


def _parse_log(log_path):
    info = {}
    if not log_path.exists():
        return info
    lines = log_path.read_text().splitlines()
    m = re.search(r"device=(\w+)", lines[0]) if lines else None
    if m:
        info["device"] = m.group(1)
    m = re.search(r"\+\s*(\d+)s\]", lines[-1]) if lines else None
    if m:
        info["wall_seconds"] = int(m.group(1))
    return info


def summarize_run(run_dir, base_cfg):
    run_dir = Path(run_dir)
    if not (run_dir / "config.yaml").exists() or not (run_dir / "metrics.jsonl").exists():
        return None
    cfg = yaml.safe_load(open(run_dir / "config.yaml"))
    rows = [json.loads(l) for l in open(run_dir / "metrics.jsonl") if l.strip()]
    val = [r for r in rows if r["split"] == "val"]
    if not val:
        return None
    key = "mpjpe" if "mpjpe" in val[0] else "local_mpjpe_cm"
    best = min(val, key=lambda r: r[key])
    last = val[-1]
    info = _parse_log(run_dir / "log.txt")
    if (run_dir / "run_info.json").exists():
        info.update(json.load(open(run_dir / "run_info.json")))
    stage = "image" if key == "local_mpjpe_cm" else "full"
    return {
        "run": str(run_dir), "stage": stage, "modalities": ",".join(cfg["model"]["modalities"]),
        "train_subjects": " ".join(cfg["data"]["train_subjects"]), "val_subjects": " ".join(cfg["data"]["val_subjects"]), "seed": cfg["seed"],
        "device": info.get("device", "?"), "git": info.get("git_commit", "?"), "epochs_run": len(val), "wall_min": round(info.get("wall_seconds", 0) / 60, 1),
        "best_epoch": best["epoch"], "best_" + key: round(best[key], 3), "last_" + key: round(last[key], 3),
        **{m: round(best[m], 2) for m in KEY_METRICS if m in best and m != key},
        "config_diff": config_diff(cfg, base_cfg), "selected_checkpoint": str(run_dir / "best.pt") if (run_dir / "best.pt").exists() else "",
    }


def build_ledger(runs_dir="runs", base_config="configs/default.yaml", out="reports/results/EXPERIMENTS.md"):
    base = load_config(base_config).to_dict()
    entries = []
    for d in sorted(Path(runs_dir).glob("**/config.yaml")):
        e = summarize_run(d.parent, base)
        if e:
            entries.append(e)
    entries.sort(key=lambda e: (e["stage"], e["run"]))
    lines = ["# Experiment ledger (generated by `meposer ledger`)", "",
             f"{len(entries)} runs under `{runs_dir}/`. Every run directory holds the resolved `config.yaml`, `log.txt`, `metrics.jsonl` and `best.pt`/`last.pt`; "
             "runs started after commit dfa272c also hold `run_info.json` (command, git commit, device, CPU, start/end, selected checkpoint); for older runs the "
             "git column is `?` and the device comes from the log. `config_diff` lists the keys that differ from "
             f"`{base_config}`; paths, worker counts and devices are omitted from the diff.", "",
             "| run | stage | modalities | val subjects | seed | device | git | epochs | wall min | best ep | best | last | PA | MPJRE | LowerPE | HandPE | jitter | config diff |",
             "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for e in entries:
        key = "local_mpjpe_cm" if e["stage"] == "image" else "mpjpe"
        diff = ", ".join(f"{k}={v}" for k, v in e["config_diff"].items() if not k.startswith("data.train_subjects") and not k.startswith("data.val_subjects"))
        lines.append(f"| {e['run']} | {e['stage']} | {e['modalities']} | {e['val_subjects']} | {e['seed']} | {e['device']} | {e['git']} | {e['epochs_run']} | {e['wall_min']} | {e['best_epoch']} | "
                     f"{e['best_' + key]} | {e['last_' + key]} | {e.get('pa_mpjpe', '')} | {e.get('mpjre', '')} | {e.get('lowerpe', '')} | {e.get('handpe', '')} | {e.get('pred_jitter', '')} | {diff} |")
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    Path(out).write_text("\n".join(lines) + "\n")
    with open(str(Path(out).with_suffix(".json")), "w") as f:
        json.dump(entries, f, indent=2, default=str)
    return out, len(entries)
